# Generated by Django 2.2.17 on 2020-11-29 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=None, max_length=200, unique=False),
            preserve_default=False,
        ),
    ]
